### ISSUE TITLE
Change the default branch to be `main` (was: `master`)

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#131]
We should follow the [current best practice](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) and change the name of the default branch. The instructions are [here](https://www.git-tower.com/learn/git/faq/git-rename-master-to-main).

**Comment by jdvorak001** [comment]
Don't forget to reconfigure [readthedocs.org](https://readthedocs.org/projects/openaire-guidelines-for-cris-managers/) and our Github Actions.

**Comment by jdvorak001** [comment]
Now when [v1.2.0](../releases/tag/v1.2.0) has been released, we should get down to this.

As a first step, I am deleting https://readthedocs.org/projects/openaire-guidelines-for-cris-managers-development/, which was used in the finalization of v1.2.0.

**Comment by jdvorak001** [comment]
Actually, [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) looks like a good fit for our needs. Quoting from the document:
> Instead of a single ``main`` branch, this workflow uses two branches to record the history of the project. The ``main`` branch stores the official release history, and the ``develop`` branch serves as an integration branch for features. It's also convenient to tag all commits in the ``main`` branch with a version number.

In this strategy ``develop`` is the default branch, whereas ``main`` tracks just the releases.

**Comment by jdvorak001** [comment]
# The main repository adapted
I have now changed the setup of the main repository. So we do not have ~~``master``~~ any more, just ``develop`` (default) and ``main``. I also deleted stale branches.

# ReadTheDocs adapted
I also reconfigured [readthedocs](https://readthedocs.org/projects/openaire-guidelines-for-cris-managers/):  I started the ``develop`` version (following the ``develop`` branch, one cannot change the name) and changed ``latest`` to follow ``main`` (only with the default version one can choose a different name).

# TODO for developers
## Adapt your forks
The easiest way to replicate this new setup in your Github fork of the main repository is to delete it and fork again.

If you don't want to do that, you should do the following (I'm pointing to [@ACz-UniBi's fork](https://github.com/ACz-UniBi/guidelines-cris-managers) for the sake of example):
- [ ] Go to the [list of branches](https://github.com/ACz-UniBi/guidelines-cris-managers) of your fork
- [ ] Delete all the branches that are not needed any more
- [ ] Add the ``develop`` branch:
  - [ ] Press the **New branch** button
  - [ ] Type in ``develop`` as the new branch name
  - [ ] Select [``openaire:develop``](https://github.com/openaire/guidelines-cris-managers/tree/develop) as the source for the branch: <img width="480" alt="image" src="https://github.com/openaire/guidelines-cris-managers/assets/7743953/1e810bc4-144e-4512-88e2-28cea268b13d">
  - [ ] Press **Create new branch**
- [ ] Set ``develop`` as the default branch
  - [ ] Go to the [Settings](https://github.com/ACz-UniBi/guidelines-cris-managers/settings) of your repository
  - [ ] In the *Default branch* section press the button with the two arrows ("Switch to another branch") and select ``develop``: <img width="852" alt="image" src="https://github.com/openaire/guidelines-cris-managers/assets/7743953/e7a3b770-1578-4194-9949-d0e5d93f0c46">
  - [ ] Press **Update** and confirm
- [ ] Back on the [list of branches](https://github.com/ACz-UniBi/guidelines-cris-managers) add the ``main`` branch, setting it to follow [``openaire:main``](https://github.com/openaire/guidelines-cris-managers/tree/main)
- [ ] And finally, delete the ``master`` branch

## Adapt your local IDE setup
Once again, the simplest approach is to delete your local project and clone it again from your updated fork.

If you do not want to do that, you'll need to do the following:
- [ ] Delete your ``master`` branch, both local and remote-tracking
- [ ] Delete your stale branches, both local and remote-tracking
- [ ] Check out ``develop`` branch as your new local branch
- [ ] Check out ``main`` branch as your new local branch
